// tslint:disable
/**
 * Freight Document primitiveization Application
 * This is the api reference for creation of 211, 210, and other EDI spec\'d shipping documents.
 *
 * The version of the OpenAPI document: 2-oas3
 * Contact: sam@freighttrust.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";
