# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the mainline branch
on:
  push:
    branches: [ mainline ]
  pull_request:
    branches: [ mainline ]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install tox
      run: python -m pip install tox
    - name: Run the sanity checks
      run: python -m tox
